### ISSUE TITLE
Chrome introduced x_google_ignoreList

### ISSUE THREAD

**Issue by jridgewell** [tc39/source-map-rfc#17]
https://developer.chrome.com/blog/devtools-better-angular-debugging/#the-x_google_ignorelist-source-map-extension

> In source maps, the new x_google_ignoreList field refers to the sources array, and lists the indices of all the known third-party sources in that source map. When parsing the source map, Chrome DevTools will use this to figure out which sections of the code should be ignore-listed.

They also call out that they're exploring how to map regions inside generated code that do not map to original code, presumably to also ignore that in the debugger:

> There may be regions in the generated code that aren’t mapped to any original code at all. We are open to exploring the possibility of such granular ignore-listing regions. Reach out if your framework or bundler would benefit from fine-grained ignore-listing!

**Comment by Jack-Works** [comment]
The typeScript team is also introducing a new extension. https://github.com/microsoft/TypeScript/pull/51307 
`x_ms_ts_annotations`

I'm very interested to see a well-known source map extension list gets maintained.

**Comment by jecfish** [comment]
Here is the dedicated docs for `x_google_ignoreList`: https://goo.gle/ignore-list

**Comment by EricSL** [comment]
Since this extension is now supported by Firefox, is there interest in renaming it to "ignoreList" or "thirdParty" and making it an official part of the spec, or are you just proposing to document common extensions as they are?

**Comment by jecfish** [comment]
For context, here is the [announcement](https://fxdx.dev/firefox-devtools-newsletter-115/#:~:text=Better%2C%20Faster%2C%20Stronger%20Debugger) from Firefox and [their docs](https://firefox-source-docs.mozilla.org/devtools-user/debugger/how_to/ignoring_sources/index.html#ignore-third-party-scripts) on how to enable it.

**Comment by EricSL** [comment]
Proposal: https://github.com/tc39/source-map-spec/pull/19

**Comment by EricSL** [comment]
The spec has been changed and the new behavior should be in Chrome DevTools 120. `x_google_ignoreList` is being renamed to `ignoreList`.

**Comment by littledan** [comment]
Closed by https://github.com/tc39/source-map-spec/pull/19

**Comment by bomsy** [comment]
Filed this to add the support the new behaviour in firefox devtools https://github.com/mozilla/source-map/issues/497
