### ISSUE TITLE
Hardening: Remove or at least warn about sections.url

### ISSUE THREAD

**Issue by jkrems** [tc39/source-map-rfc#29]
Index maps in the spec support putting each section into a separate resource, linking via the `url` field. In practice, few (if any) tools actually support this. If that's the case, it may be less confusing to remove it from the spec.

**Comment by littledan** [comment]
Do any tools support this? Do browsers support it?

If this feature doesn't match implementations, we should remove it.

**Comment by jkrems** [comment]
@mitsuhiko We're actively using them and it would be non-trivial to replace them. We assemble JS in production dynamically and do the same for the source maps for those responses. Parsing and merging the source map fragments would be fairly (and very likely too) expensive.

**Comment by littledan** [comment]
@mitsuhiko Let's break out the discussion about indexed source maps into a separate issue then?

Here, let's focus on the `url` field. Does anyone have information compiled about the implementation reality?

**Comment by bmeurer** [comment]
Chromium DevTools supports index maps (and has always supported them), but does not support the `url` field in the `sections`.

Regarding tools: @sokra recently filed an issue regarding performance of index maps in Chrome DevTools, which might indicate that webpack and/or turbopack might be using them as well soon(ish)? 😄

**Comment by mitsuhiko** [comment]
I separated out the wider discussion about the index maps.

**Comment by bomsy** [comment]
I can confirm the same for https://github.com/mozilla/source-map which is used by Firefor DevTools ( and maybe used by other tools) that indexed sourcemaps are supported but not the `url` field.
