### ISSUE TITLE
Create a process document

### ISSUE THREAD

**Issue by jkup** [tc39/source-map-rfc#55]
I'm not sure if this conversation has been started elsewhere but it would be good to start a discussion on how new features can move through our task group and make it into the spec.

TC39 has this great process document: https://tc39.es/process-document/

For example, the next time someone wants to add a new field to source maps (like https://github.com/tc39/source-map-rfc/issues/25) - we should have a process document on how to submit a proposal, how we move proposals forward, a list of tools and browsers we work with, how many "implementers" it takes to ship something, etc.

**Comment by littledan** [comment]
We have https://github.com/tc39/source-map-rfc/blob/main/PROCESS.md . Does that meet the requirements for this issue? Does anyone have further recommendations or concerns?

**Comment by jkup** [comment]
Perfect!
