### ISSUE TITLE
Current inlining information looses outer scopes of the inlined function

### ISSUE THREAD

**Issue by szuend** [tc39/source-map-rfc#61]
Live example here: https://szuend.github.io/scope-proposal-examples/05_inline_across_modules/inline_across_modules.html

Given the following example:

**module.js**

```js
export const MODULE_CONSTANT = 'module_constant';

export class Logger {
  static CLASS_CONSTANT = 42;

  static log(x) {
    console.log(x);
  }
}
```

**inline_across_modules.js**

```js
import {Logger} from './module.js';

function inner(x) {
  Logger.log(x);
}

function outer(x) {
  inner(x);
}

outer(42);
outer(null);
```

with **bundle.js**

```js
console.log(42);console.log(null);
```

produced by Closure JS via

```sh
google-closure-compiler --compilation_level ADVANCED inline_across_modules.js module.js --js_output_file bundle.min.js --create_source_map bundle.min.js.map --source_map_include_content --language_in UNSTABLE
```

Lets say we put a breakpoint on the `console.log(x)` line in `module.js`. Once we pause we don't have the surrounding scope information of `static log(x)`. E.g. we don't know that the function was inside the `Logger` class scope, which in turn was in a module scope. We _could_ make `MODULE_CONSTANT` and `CLASS_CONSTANT` available via bindings, but a debuggers scope view would have to make it look like those two were defined inside the `static log(x)` scope.

The only solution I could come up with is to include the scope trees of each original source file as well (similar to how DWARF does it). But I'm curious what folks think.

From a DevTools/debugger perspective this info would be very much needed. Parsing the original sources and constructing a scope tree is not enough (missing bindings info).

**Comment by hbenl** [comment]
I think there's a misunderstanding here: the [proposal calls for](https://github.com/tc39/source-map-rfc/blob/8bfbb5cb11941efa56fa9e833917ff39b28f2bbf/proposals/scopes.md?plain=1#L99) including all the original scopes containing the original location. So the function scope for `log()`, the class scope for `Logger` and the module scope for `module.js` would be included.
In this example the sourcemap should include the following scopes for the `console.log(42);` statement:
- the module scope for `inline_across_modules.js`
- the function scope for `outer`
- the function scope for `inner`
- the function scope for `log`
- the class scope for `Logger`
- the module scope for `module.js`

All of these scopes except the module scope for `inline_across_modules.js` would have to be repeated for the `console.log(null);` statement, so explicitly encoding original scopes (like in #62) could be more efficient.

**Comment by szuend** [comment]
Thanks for the clarification! Just to make sure I understand correctly, the nesting of scopes would look like this:

- the module scope for `inline_across_modules.js`
  - the function scope for `outer`
    - the function scope for `inner`
      - the module scope for `module.js` (with the "inherit parent bindings" flag set to `false`)
        - the class scope for `Logger`
          - the function scope for `log`
  - the function scope for `outer`
    - ...
