### ISSUE TITLE
Work with a web standards organization

### ISSUE THREAD

**Issue by tromey** [tc39/source-map-rfc#7]
I think it would be good to turn the source map spec into a real web standard.

**Comment by littledan** [comment]
This seems like a good idea to me, in particular so that the exact IP status of the source maps specification can be worked out.

**Comment by codehag** [comment]
We have started to discuss this here: https://github.com/WebAssembly/design/pull/1051 with the initial meeting notes here: https://docs.google.com/document/d/1mMFN-OksiJZm1PD3XmBpAVq0vhT0df1rGKwYq2jfn58/edit#heading=h.kpbqwvejdlrw

**Comment by bomsy** [comment]
I think we should also actively begin to think about and pursue this as part of the work to tighten the current spec. i know we discussed it under the TC39 group. Would it go under that standards body or are there other options to go with?

**Comment by littledan** [comment]
Working within a standards organization will be important to ensure fully royalty-free licensing of any related intellectual property. It will also have benefits in terms of providing a well-defined open structure for participation and evolution over time.

The options I see for standards organization are:
- [My preference] In TC39, as a separate document maintained outside of ECMA-262. (We may consider forming a separate task group for this purpose, but we can start out informal.) I'd like to raise this question to the committee in the late May 2023 TC39 meeting, but let's review this in the early May TC39 tools call to see if participants are generally in favor of that.
- [Another good option] If TC39 is skeptical of hosting the source maps standards effort, I'd encourage us to work within WICG in the near term, to ensure intellectual property protection. We can figure out a formal home later. WHATWG and W3C would both be possibilities.

**Comment by jkup** [comment]
Closing as we now are part of TC39.
