### ISSUE TITLE
Scopes: support default parameter initializers

### ISSUE THREAD

**Issue by hbenl** [tc39/source-map-rfc#78]
From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters):
> The default parameter initializers live in their own scope, which is a parent of the scope created for the function body.

To support this we need to add some information for function scopes:
- which of the scope's variables are parameters
- the location range for the special scope for default parameter initializers (i.e. the location range of the function's parameter declarations)

**Comment by szuend** [comment]
I'm not sure about sibling scopes, but we could handle it similar to how JS engines do this. (See [this comment](https://github.com/tc39/source-map-rfc/pull/75#issuecomment-1990573742)):

* The function scope starts at the opening paren of the function declaration. It contains the parameters.
* If default initializers are used, emit a child block scope that starts at the opening brace, but contains the full function body.

**Comment by hbenl** [comment]
> I'm not sure about sibling scopes, but we could handle it similar to how JS engines do this.

Right, and actually the documentation at MDN also suggests this (because it says the extra scope should be the parent of the function body's scope) and this is also more efficient (because we don't need to repeat the function parameters).

> If default initializers are used, emit a child block scope that starts at the opening brace, but contains the full function body.

Actually I found that the extra scope is only created when it's absolutely necessary: when default initializers are used *and* one of the initializers references a variable that is redeclared in the function's body.
This is important because we need to match the scopes we get from the debugger to the `GeneratedRange`s described in the sourcemap in order to compute the original scopes.

**Comment by hbenl** [comment]
> I found that the extra scope is only created when it's absolutely necessary: when default initializers are used and one of the initializers references a variable that is redeclared in the function's body.

I was wrong about this - it seems the extra scope is created when default initializers are used and there is a variable declaration in the body. Generally JS engines seem to omit scopes without bindings.

**Comment by hbenl** [comment]
I've added [examples](https://github.com/hbenl/tc39-proposal-scope-mapping/commit/fd93d9616feb885112c3530b05985b9d07b64617) showing how this can be done using the current proposal.
